# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, unique=True)),
                ('app_name', models.CharField(max_length=256)),
                ('developer_name', models.CharField(max_length=128)),
                ('developer_email', models.EmailField(max_length=128)),
                ('icon_url', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='terms',
            field=models.ManyToManyField(related_name='apps', to='core.Term'),
        ),
    ]
