# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='developer_email',
            field=models.EmailField(max_length=128, null=True),
        ),
    ]
